apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-deployment
  labels:
    app: curso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curso
  template:
    metadata:
      labels:
        app: curso
    spec:
      containers:
      - name: estudante-container
        image: vilianeso/academyio.cursos.api:latest        
        ports:
        - containerPort: 5078
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:5078"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
