apiVersion: apps/v1
kind: Deployment
metadata:
  name: identidade-deployment
  labels:
    app: identidade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identidade
  template:
    metadata:
      labels:
        app: identidade
    spec:
      containers:
      - name: identidade-container
        image: vilianeso/academyio.auth.api:latest        
        ports:
        - containerPort: 5077
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:5077"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
