apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
  labels:
    app: pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      containers:
      - name: pagamento-container
        image: vilianeso/academyio.pagamentos.api:latest        
        ports:
        - containerPort: 5272
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:5272"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
