apiVersion: v1
kind: Service
metadata:
  name: identidade-service
spec:  
  selector:
    app: identidade    
  ports:  
      - protocol: TCP  
        port: 5077         # porta interna do servi√ßo
        targetPort: 5077   # porta do container
  type: NodePort