apiVersion: v1
kind: Service
metadata:
  name: pagamento-service
spec:  
  selector:
    app: pagamento    
  ports:  
      - protocol: TCP  
        port: 5272         # porta interna do servi√ßo
        targetPort: 5272   # porta do container
        nodePort: 30080    # Porta fixa para acesso externo
  type: NodePort