apiVersion: v1
kind: Service
metadata:
  name: identidade-service
spec:
  type: NodePort
  selector:
    app: identidade    # precisa bater com o label do seu Deployment
  ports:    
      - port: 80         # porta interna do serviço
        targetPort: 80   # porta do container
        nodePort: 30080  # porta exposta no nó do cluster