apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:  
  selector:
    app: bff    
  ports:  
      - protocol: TCP  
        port: 5018         # porta interna do servi√ßo
        targetPort: 5018   # porta do container
        nodePort: 30081    # Porta fixa para acesso externo
  type: NodePort