apiVersion: v1
kind: Service
metadata:
  name: estudante-service
spec:  
  selector:
    app: estudante    
  ports:  
      - protocol: TCP  
        port: 5275         # porta interna do servi√ßo
        targetPort: 5275   # porta do container
        nodePort: 30078   # Porta fixa para acesso externo
  type: NodePort