apiVersion: v1
kind: Service
metadata:
  name: identidade-service
spec:
  type: LoadBalancer   # <- muda de NodePort para LoadBalancer
  selector:
    app: identidade    # precisa bater com o label do seu Deployment
  ports:
    - protocol: TCP
      port: 80         # porta interna do serviÃ§o
      targetPort: 80   # porta do container