apiVersion: v1
kind: Service
metadata:
  name: sqlserver-curso-service
spec:
  selector:
    app: sqlserver-curso
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
  type: ClusterIP
