apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-identidade-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-identidade
  template:
    metadata:
      labels:
        app: sqlserver-identidade
    spec:
      containers:
        - name: sqlserver-identidade
          image: vilianeso/academyio.sqlserver.identidade:latest
          ports:
            - containerPort: 1433   # porta padr√£o do SQL Server
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "MeuDB@123"
